version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: payment_processor_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M

  api1:
    build: .
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/payment_processor_prod
      PORT: 9999
      MIX_ENV: prod
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  api2:
    build: .
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/payment_processor_prod
      PORT: 9999  
      MIX_ENV: prod
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M

volumes:
  postgres_data: