services:
  coordinator:
    build: ./queue_coordinator
    hostname: coordinator
    environment:
      MIX_ENV: prod
      ERL_MAX_PORTS: 2048
      ELIXIR_ERL_OPTIONS: "+K true +A 4 -kernel inet_dist_listen_min 9100 inet_dist_listen_max 9100"
      ERL_COOKIE: "rinha_cluster_cookie"
      ERL_EPMD_PORT: 4369
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  api1:
    build: .
    hostname: api1
    environment:
      SECRET_KEY_BASE: "VvoX+B2qGQFBpIYKnKOqfKsLJ5w9O5fSBW9qK9BqP7W5/K2GFp7+DqXGJ8WBqP3Q"
      PORT: 9999
      MIX_ENV: prod
      PHX_SERVER: true
      ERL_MAX_PORTS: 2048
      ELIXIR_ERL_OPTIONS: "+K true +A 4 -kernel inet_dist_listen_min 9101 inet_dist_listen_max 9101"
      ERL_COOKIE: "rinha_cluster_cookie"
      NODE_NAME: "api1"
      COORDINATOR_URL: "http://coordinator:8080"
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  api2:
    build: .
    hostname: api2
    environment:
      SECRET_KEY_BASE: "VvoX+B2qGQFBpIYKnKOqfKsLJ5w9O5fSBW9qK9BqP7W5/K2GFp7+DqXGJ8WBqP3Q"
      PORT: 9999  
      MIX_ENV: prod
      PHX_SERVER: true
      ERL_MAX_PORTS: 2048
      ELIXIR_ERL_OPTIONS: "+K true +A 4 -kernel inet_dist_listen_min 9102 inet_dist_listen_max 9102"
      ERL_COOKIE: "rinha_cluster_cookie"
      NODE_NAME: "api2"
      COORDINATOR_URL: "http://coordinator:8080"
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    networks:
      - payment-processor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 20M

networks:
  payment-processor:
    external: true
    name: payment-processor